CREATE PROCEDURE DatabaseDrop AS
	BEGIN
		-- Switch to the newly created or existing database
		EXEC('USE [Examination System]');

		-- Drop tables if they exist (starting from dependent to independent tables)
		IF OBJECT_ID('dbo.STUDENT_PHONE', 'U') IS NOT NULL DROP TABLE dbo.STUDENT_PHONE;
		IF OBJECT_ID('dbo.BRANCH_DEPARTMENT', 'U') IS NOT NULL DROP TABLE dbo.BRANCH_DEPARTMENT;
		IF OBJECT_ID('dbo.BRANCH', 'U') IS NOT NULL DROP TABLE dbo.BRANCH;
		IF OBJECT_ID('dbo.HIRING', 'U') IS NOT NULL DROP TABLE dbo.HIRING;
		IF OBJECT_ID('dbo.FREELANCING', 'U') IS NOT NULL DROP TABLE dbo.FREELANCING;
		IF OBJECT_ID('dbo.STUDENT_CERTIFICATE', 'U') IS NOT NULL DROP TABLE dbo.STUDENT_CERTIFICATE;
		IF OBJECT_ID('dbo.CERTIFICATE', 'U') IS NOT NULL DROP TABLE dbo.CERTIFICATE;
		IF OBJECT_ID('dbo.STUDENT_COURSE', 'U') IS NOT NULL DROP TABLE dbo.STUDENT_COURSE;
		IF OBJECT_ID('dbo.CHOICE', 'U') IS NOT NULL DROP TABLE dbo.CHOICE;
		IF OBJECT_ID('dbo.STUDENT_ANSWER', 'U') IS NOT NULL DROP TABLE dbo.STUDENT_ANSWER;
		IF OBJECT_ID('dbo.QUESTION', 'U') IS NOT NULL DROP TABLE dbo.QUESTION;
		IF OBJECT_ID('dbo.EXAM', 'U') IS NOT NULL DROP TABLE dbo.EXAM;
		IF OBJECT_ID('dbo.TOPIC', 'U') IS NOT NULL DROP TABLE dbo.TOPIC;
		IF OBJECT_ID('dbo.COURSE', 'U') IS NOT NULL DROP TABLE dbo.COURSE;
		IF OBJECT_ID('dbo.INSTRUCTOR', 'U') IS NOT NULL DROP TABLE dbo.INSTRUCTOR;
		IF OBJECT_ID('dbo.STUDENT', 'U') IS NOT NULL DROP TABLE dbo.STUDENT;
		IF OBJECT_ID('dbo.DEPARTMENT', 'U') IS NOT NULL DROP TABLE dbo.DEPARTMENT;

		PRINT 'All Tables Have Been Deleted Successfully.';
	END;